### ISSUE TITLE
[Feature] 데이터베이스 환경 셋팅

### ISSUE THREAD

**Issue by loveAlakazam** [toy-squad/toy-squad-nest#1]
## Todo List

- [ ] aws rds mysql 인스턴스와 프로젝트 연결하기
- [x] typeorm 환경 셋팅
- [x] `.env` 파일로 인스턴스정보와 포트정보 관리하기

**Comment by loveAlakazam** [comment]
- 지원님 이슈 셋팅하는 방법 알려주기
- 지원님도 프로젝트 셋팅이 잘되는지 확인

```
$ npm install 
```
